export const schemaStatements = [
  `CREATE TABLE IF NOT EXISTS species (
    id INTEGER PRIMARY KEY,
    reino TEXT NOT NULL,
    genero_id INTEGER NOT NULL,
    nombre_cientifico TEXT NOT NULL,
    nombre_comun TEXT NOT NULL,
    autor_cientifico TEXT,
    descripcion TEXT NOT NULL,
    habitat TEXT NOT NULL,
    distribucion_chiloe TEXT NOT NULL,
    endemica INTEGER NOT NULL,
    estado_conservacion TEXT NOT NULL,
    fuentes TEXT NOT NULL,
    geo_lat REAL,
    geo_lng REAL,
    atributos_especificos TEXT NOT NULL,
    foto_portada_key TEXT,
    fotos_keys TEXT NOT NULL,
    creado_por INTEGER,
    revisado_por INTEGER,
    fecha_revision TEXT,
    created_at TEXT,
    updated_at TEXT,
    imagenes_urls TEXT NOT NULL,
    genero_nombre TEXT
  )`,
  'CREATE INDEX IF NOT EXISTS idx_species_reino ON species(reino)',
  'CREATE INDEX IF NOT EXISTS idx_species_nombre_comun ON species(nombre_comun)',
  `CREATE TABLE IF NOT EXISTS sync_state (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS local_avistamientos (
    local_id TEXT PRIMARY KEY,
    remote_id INTEGER,
    especie_id INTEGER,
    reino TEXT NOT NULL,
    nombre_sugerido TEXT,
    descripcion TEXT,
    foto_key TEXT NOT NULL,
    local_photo_path TEXT,
    geo_lat REAL NOT NULL,
    geo_lng REAL NOT NULL,
    precision_metros REAL,
    observado_en TEXT NOT NULL,
    estado TEXT NOT NULL,
    sync_status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  'CREATE INDEX IF NOT EXISTS idx_local_avistamientos_sync_status ON local_avistamientos(sync_status)',
  `CREATE TABLE IF NOT EXISTS mutation_queue (
    id TEXT PRIMARY KEY,
    type TEXT NOT NULL,
    payload TEXT NOT NULL,
    status TEXT NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    last_error TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  'CREATE INDEX IF NOT EXISTS idx_mutation_queue_status ON mutation_queue(status, created_at)',
];
